#!/usr/bin/env python3
"""Generate docs/governance/adrs/README.md (Appendix F, the ADR Registry) from the
ADR files' frontmatter.

The registry is a derived index: the ADR files are the source of truth
(DEC-a4e550), this file is navigation. Run it after any ADR change:

    npm run docs:generate:adr-registry

It reuses the frontmatter parser of audit_adrs.py so both tools read the
files the same way. Files whose name is not ADR-<six hex>.md are listed with a
note; a file that self-quarantines (superseded_by its own uid) is listed as
quarantined. Nothing is edited by hand in the generated body.
"""
from __future__ import annotations

import re
import subprocess
import sys
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from audit_adrs import ADR_DIR, ROOT, as_list, parse_frontmatter  # noqa: E402

README = ADR_DIR / "README.md"
CANONICAL_NAME = re.compile(r"^ADR-[0-9a-f]{6}\.md$")
FRONTMATTER = """---
id: appendix-f-adrs
title: "Appendix F — ADR Registry"
appendix: F
status: drafting
authority: authoritative
generator: scripts/docs-control/generate_adr_registry.py
---
"""


def git_head() -> str:
    try:
        return subprocess.check_output(["git", "rev-parse", "--short", "HEAD"], cwd=ROOT, text=True).strip()
    except Exception:  # noqa: BLE001
        return "unknown"


def cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ").strip()


def main() -> int:
    rows = []
    status_counter: Counter[str] = Counter()
    noncanonical = []
    quarantined = []
    for path in sorted(ADR_DIR.glob("*.md")):
        if path.name == "README.md":
            continue
        fm = parse_frontmatter(path.read_text(encoding="utf-8"))
        uid = str(fm.get("uid") or "")
        status = str(fm.get("status") or "")
        title = str(fm.get("title") or path.stem)
        supersedes = ", ".join(as_list(fm.get("supersedes")))
        superseded_by = ", ".join(as_list(fm.get("superseded_by")))
        note = ""
        if not CANONICAL_NAME.match(path.name):
            noncanonical.append(path.name)
            note = "non-canonical filename"
        if uid and superseded_by == uid:
            quarantined.append(path.name)
            note = "quarantined duplicate"
        else:
            status_counter[status or "(none)"] += 1
        rows.append((uid, f"| `{cell(uid)}` | [{cell(title)}](./{path.name}) | {cell(status)} | {cell(supersedes)} | {cell(superseded_by)} | {cell(note)} |"))
    rows.sort(key=lambda r: r[0])
    total = sum(status_counter.values())
    counts = ", ".join(f"{k} {v}" for k, v in sorted(status_counter.items()))
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    out = [FRONTMATTER, "", "# Appendix F — ADR Registry", "",
           "The ADR Registry is the canonical index of platform decisions. Each entry has a structurally unique UID (`DEC-xxxxxx`) used in cross-references throughout the documentation. The ADR files are the source of truth (DEC-a4e550); this registry is generated from their frontmatter and is never edited by hand.",
           "",
           f"**Counts at generation.** {total} records: {counts}. Quarantined duplicates (not counted): {len(quarantined)} ({', '.join(quarantined) or 'none'}). Non-canonical filenames: {len(noncanonical)} ({', '.join(noncanonical) or 'none'}).",
           "",
           "**Hygiene.** The supersession pair rule (DEC-623f8f rule 1) is enforced on every push and pull request by `.github/workflows/adr-hygiene.yml` running `scripts/docs-control/audit_adrs.py`. That auditor's report is `docs-control/reports/adr-hygiene.md`. See erratum ADR-ERR-005 for the rules DEC-623f8f names that are not built.",
           "",
           "| UID | Title | Status | Supersedes | Superseded by | Note |",
           "|---|---|---|---|---|---|"]
    out.extend(r for _, r in rows)
    out.append("")
    out.append(f"*Generated by `scripts/docs-control/generate_adr_registry.py` from bc-docs `{git_head()}` at {generated_at}.*")
    README.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"wrote {README.relative_to(ROOT)}: {total} records, {len(quarantined)} quarantined, {len(noncanonical)} non-canonical")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
